blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/orgs/Clearfracture/discussions
    about: Please ask and answer questions here.
  - name: ðŸ“š Documentation
    url: https://github.com/orgs/Clearfracture
    about: Check our documentation for more information.

